#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IO.Vov.Vitamio.Demo.Resource", IsApplication=true)]

namespace IO.Vov.Vitamio.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int mediacontroller_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int mediacontroller_bg_pressed = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int transparent = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int mediacontroller_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int mediacontroller_pause = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int mediacontroller_play = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mediacontroller_screen_fit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mediacontroller_screen_size = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mediacontroller_sreen_size_100 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int mediacontroller_sreen_size_crop = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int scrubber_control_disabled_holo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int scrubber_control_focused_holo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int scrubber_control_normal_holo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int scrubber_control_pressed_holo = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int scrubber_control_selector_holo = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int scrubber_primary_holo = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int scrubber_progress_horizontal_holo_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int scrubber_secondary_holo = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int scrubber_track_holo_dark = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000f
			public const int buffer = 2131230735;
			
			// aapt resource value: 0x7f080015
			public const int button1 = 2131230741;
			
			// aapt resource value: 0x7f08000c
			public const int dd = 2131230732;
			
			// aapt resource value: 0x7f080011
			public const int download_rate = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int load_rate = 2131230738;
			
			// aapt resource value: 0x7f080009
			public const int localaudio = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int localvideo = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int localvideo_setsurface = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int mediacontroller_file_name = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int mediacontroller_play_pause = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int mediacontroller_seekbar = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int mediacontroller_time_current = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int mediacontroller_time_total = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int probar = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int start = 2131230740;
			
			// aapt resource value: 0x7f080008
			public const int streamvideo = 2131230728;
			
			// aapt resource value: 0x7f08000b
			public const int sub1 = 2131230731;
			
			// aapt resource value: 0x7f08000e
			public const int subtitle_view = 2131230734;
			
			// aapt resource value: 0x7f08000a
			public const int surface = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int surface_view = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int textView = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int url = 2131230739;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int media_metadata = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int mediacontroller = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int mediaplayer_1 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int mediaplayer_2 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int mediaplayer_3 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int subtitle1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int subtitle2 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int videobuffer = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int videoview = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int libarm = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int test_cbr = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int VideoView_error_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int VideoView_error_text_invalid_progressive_playback = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int VideoView_error_text_unknown = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int VideoView_error_title = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int action_settings = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int local_audio = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int local_video = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int local_video_setsurface = 2131099663;
			
			// aapt resource value: 0x7f060004
			public const int mediacontroller_play_pause = 2131099652;
			
			// aapt resource value: 0x7f06001b
			public const int openvideo1 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int openvideo2 = 2131099676;
			
			// aapt resource value: 0x7f060005
			public const int permission_group_tools_description = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int permission_group_tools_label = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int permission_receive_messages_description = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int permission_receive_messages_label = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int permission_write_providers_description = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int permission_write_providers_label = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int res_audio = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int stream_video = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int subtitle1 = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int subtitle12 = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int title_activity_media_player_subtitle = 2131099671;
			
			// aapt resource value: 0x7f06001a
			public const int title_activity_video_buffer = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int title_activity_video_subtitle_demo = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int title_activity_video_subtitle_list = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int title_activity_video_view_subtitle = 2131099672;
			
			// aapt resource value: 0x7f06000d
			public const int vitamio_demo_name = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int vitamio_init_decoders = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int vitamio_library_app_name = 2131099660;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MediaController_SeekBar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MediaController_Text = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int NoActionBar = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
